### ISSUE TITLE
error on gulp command

### ISSUE THREAD

**Issue by zainali95** [unbug/generator-webappstarter#6]
gulp
module.js:557
    throw err;
    ^

Error: Cannot find module 'vinyl-source-stream'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/zainali95/Desktop/webapp-compass/gulpfile.js:7:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

**Comment by unbug** [comment]
Can you try to install `vinyl-source-stream` manually? I think the problem might be because `generator-webappstarter` is not ready for `node 6.9.4`+.
